// <auto-generated />
using System;
using Auth0Admin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Auth0Admin.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20210609210357_TokenTable")]
    partial class TokenTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Auth0Admin.Data.AccessToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpiresIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scope")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("Auth0Admin.Data.EventInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeaturedImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("_ImageUrls")
                        .HasColumnType("TEXT")
                        .HasColumnName("ImageUrls");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Fundraising",
                            DateTime = new DateTime(2019, 12, 25, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Spend an elegant night of dinner and dancing with us as we raise money for our new rescue farm.",
                            FeaturedImageUrl = "https://placekitten.com/500/500",
                            Location = "1234 Fancy Ave.",
                            Name = "Charity Ball",
                            _ImageUrls = "[\"https://placekitten.com/500/500\", \"https://placekitten.com/500/500\", \"https://placekitten.com/500/500\"]"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Adoptions",
                            DateTime = new DateTime(2019, 11, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Come to our donation drive to help us replenish our stock of pet food, toys, bedding, etc. We will have live bands, games, food trucks, and much more.",
                            FeaturedImageUrl = "https://placekitten.com/500/500",
                            Location = "1234 Dog Alley",
                            Name = "Rescue Center Goods Drive",
                            _ImageUrls = "[\"https://placekitten.com/500/500\"]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
